def remote = [:]

pipeline {
    agent any
    parameters {
        gitParameter(type: 'PT_BRANCH', name: 'BRANCH_TO_BUILD', branchFilter: 'origin/(.*)', defaultValue: 'main', selectedValue: 'DEFAULT', sortMode: 'DESCENDING_SMART')
        choice(name: 'ENV', choices: ['dev', 'demo', 'prod'], description: 'Select environment')
        booleanParam(name: 'CLEAR_CACHE', defaultValue: false)
    }

    environment {
        PRJ_DIR='/var/www/plant-shop'
        //SLACK=credentials('token')
        //CHANNEL_ID=""
        GIT_URL="https://github.com/AnastasiyaGapochkina01/plant-shop-m2.git"
    }

    stages {
        stage('Set env to deploy'){
            steps {
                script {
                    switch(params.ENV) {
                        case 'dev':
                            env.HOST = '3.129.207.52'
                            break
                        case 'demo':
                            env.HOST = '3.129.207.52'
                            break
                        case 'prod':
                            env.HOST = '3.129.207.52'
                            break
                        default:
                            env.HOST = '3.129.207.52'
                    }
                    echo "HOST set to: ${env.HOST}"
                }
            }
        }

        stage('Prepare Credentials') {
            steps {
                withCredentials([sshUserPrivateKey(credentialsId: 'jenkins-key', usernameVariable: 'username', keyFileVariable: 'private_key')]) {
                    script {
                        remote.name = "${env.HOST}"
                        remote.host = "${env.HOST}"
                        remote.user = "${username}"
                        remote.identity = readFile "${private_key}"
                        remote.allowAnyHosts = true
                    }
                }
           }
        }

        stage('Checkout branch to build') {
            steps {
                script {
                    def RELEASE = sh(script: 'date +%Y-%m-%d_%s', returnStdout: true).trim()
                    def RELEASE_DIR = "${env.PRJ_DIR}/release-${RELEASE}"
                    sshCommand remote: remote, command: """
                        sudo -u www-data bash -c 'git clone -b ${params.BRANCH_TO_BUILD} ${env.GIT_URL} ${RELEASE_DIR}'
                    """
                    env.RELEASE_DIR = "${RELEASE_DIR}"
                }
            }
        }

        stage('Deploy M2') {
            steps {
                script {
                    sshCommand remote: remote, command: """
                        cd ${env.RELEASE_DIR}
                        su - www-data -s php bin/magento setup:upgrade
                        su - www-data -sphp bin/magento setup:di:compile
                        su - www-data -s php bin/magento setup:static-content:deploy en_US ru_RU -f
                    """
                }
            }
        }

        stage('Switch release') {
            steps {
                script {
                    sshCommand remote: remote, command: """
                        cd ${env.PRJ_DIR}
                        su - www-data -s ln -sf ${env.RELEASE_DIR} ${env.PRJ_DIR}/current
                    """
                }
            }
        }

        stage('Clear cache') {
            when {
                expression { params.CLEAR_CACHE }
            }
            steps {
                script {
                    sshCommand remote: remote, command: """
                        cd ${env.RELEASE_DIR}
                        su - www-data -s php bin/magento cache:flush
                    """
                }
            }
        }


    }
}
